name: Pytest
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./python
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest --junit-xml=junit.xml test.py
    - name: Report to Ultralight
      if: always()
      uses: ultralightlabs/ultralight-github-action@main
      with:
        ultralight-secret-key: ${{secrets.ULTRALIGHT_GH_ACTION_SECRET_KEY}}
        test-report-path: python/junit.xml
        test-steps-directory-path: python/test_protocols
        ultralight-url: https://staging.ultralightlabs.com
        ultralight-product-id: ${{secrets.ULTRALIGHT_GH_ACTION_PRODUCT_ID}}

